-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.sala
(
    id uuid NOT NULL,
    nombre character varying NOT NULL,
    tipo_sala_id uuid NOT NULL,
    estado_sala_id uuid NOT NULL,
    created_at time with time zone NOT NULL,
    updated_at time with time zone NOT NULL,
    area numeric NOT NULL,
    altura numeric NOT NULL,
    volumen numeric NOT NULL,
    posee_intraccion boolean NOT NULL,
    posee_extraccion boolean NOT NULL,
    posee_co2 boolean NOT NULL,
    posee_ins_agua boolean NOT NULL,
    organizacion_id uuid NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tipo_sala
(
    id uuid NOT NULL,
    nombre character varying NOT NULL,
    descripcion character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.estado_sala
(
    id uuid NOT NULL,
    nombre character varying NOT NULL,
    descripcion text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.organizacion
(
    id uuid NOT NULL,
    nombre character varying NOT NULL,
    localizacion character varying NOT NULL,
    descripcion text NOT NULL,
    created_at time with time zone NOT NULL,
    updated_at time with time zone NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.usuario
(
    id uuid NOT NULL,
    nombre character varying NOT NULL,
    estado_id character varying NOT NULL,
    email character varying NOT NULL,
    password_hash character varying NOT NULL,
    created_at time with time zone NOT NULL,
    updated_at time with time zone NOT NULL,
    rol_id uuid NOT NULL,
    organizacion_id uuid NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.rol
(
    id uuid NOT NULL,
    nombre character varying NOT NULL,
    descripcion character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."planta "
(
    id uuid NOT NULL,
    nombre character varying NOT NULL,
    created_at time with time zone NOT NULL,
    updated_at time with time zone NOT NULL,
    fecha_inicio date NOT NULL,
    cultivo_id uuid NOT NULL,
    estado_planta_id uuid NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.evento
(
    id uuid NOT NULL,
    created_at time with time zone NOT NULL,
    updated_at time with time zone NOT NULL,
    tipo_evento_id uuid NOT NULL,
    descripcion text NOT NULL,
    fecha_inicio date NOT NULL,
    estado_evento_id uuid NOT NULL,
    usuario_id uuid NOT NULL,
    timeline_id uuid NOT NULL,
    cultivo_id uuid NOT NULL,
    planta_id uuid,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.registro
(
    id uuid NOT NULL,
    fecha_registro time with time zone NOT NULL,
    nombre character varying NOT NULL,
    parametro_temperatura numeric NOT NULL,
    parametro_humedad numeric NOT NULL,
    parametro_vpd numeric NOT NULL,
    parametro_co2 numeric,
    created_at time with time zone NOT NULL,
    updated_at time with time zone NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.planificacion
(
    id uuid NOT NULL,
    nombre character varying NOT NULL,
    prioridad_id uuid NOT NULL,
    tipo_planificacion_id uuid NOT NULL,
    estado_planificacion_id uuid NOT NULL,
    fecha_planificacion date NOT NULL,
    fecha_fin_planificacion date,
    duracion_hs numeric,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."timeLine"
(
    id uuid NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."tipoEvento"
(
    id uuid NOT NULL,
    nombre character varying NOT NULL,
    descripcion text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."estadoEvento"
(
    id uuid NOT NULL,
    estado character varying NOT NULL,
    descripcion text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."faseCultivo"
(
    id uuid NOT NULL,
    nombre character varying NOT NULL,
    descripcion character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.cultivo
(
    id uuid NOT NULL,
    nombre character varying NOT NULL,
    fecha_inicio date NOT NULL,
    duracion_estimada numeric NOT NULL,
    fase_id uuid NOT NULL,
    estado_cultivo_id uuid NOT NULL,
    sala_id uuid NOT NULL,
    usuario_responsable_id uuid NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."estadoPlanta"
(
    id uuid NOT NULL,
    nombre character varying NOT NULL,
    descripcion text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."cultivoVariedad"
(
    id uuid NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."catalogoVariedad"
(
    id uuid NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.sala
    ADD FOREIGN KEY (id)
    REFERENCES public.cultivo (sala_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tipo_sala
    ADD FOREIGN KEY (id)
    REFERENCES public.sala (tipo_sala_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.estado_sala
    ADD FOREIGN KEY (id)
    REFERENCES public.sala (estado_sala_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.organizacion
    ADD FOREIGN KEY (id)
    REFERENCES public.sala (organizacion_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.organizacion
    ADD FOREIGN KEY (id)
    REFERENCES public.usuario (rol_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.usuario
    ADD FOREIGN KEY (id)
    REFERENCES public.cultivo (usuario_responsable_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.rol
    ADD FOREIGN KEY (id)
    REFERENCES public.usuario (rol_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."planta "
    ADD FOREIGN KEY (id)
    REFERENCES public.evento (planta_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."timeLine"
    ADD FOREIGN KEY (id)
    REFERENCES public.evento (timeline_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."tipoEvento"
    ADD FOREIGN KEY (id)
    REFERENCES public.evento (tipo_evento_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."estadoEvento"
    ADD FOREIGN KEY (id)
    REFERENCES public.evento (estado_evento_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."faseCultivo"
    ADD FOREIGN KEY (id)
    REFERENCES public.cultivo (fase_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.cultivo
    ADD FOREIGN KEY (id)
    REFERENCES public.evento (cultivo_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."estadoPlanta"
    ADD FOREIGN KEY (id)
    REFERENCES public."planta " (estado_planta_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;