-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS public.sala
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    nombre character varying NOT NULL,
    tipo_sala_id uuid NOT NULL,
    estado_sala_id uuid NOT NULL,
    created_at time with time zone NOT NULL,
    updated_at time with time zone NOT NULL,
    area numeric NOT NULL,
    altura numeric NOT NULL,
    volumen numeric NOT NULL,
    posee_intraccion boolean NOT NULL,
    posee_extraccion boolean NOT NULL,
    posee_co2 boolean NOT NULL,
    posee_ins_agua boolean NOT NULL,
    organizacion_id uuid NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tipo_sala
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    nombre character varying NOT NULL,
    descripcion character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.estado_sala
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    nombre character varying NOT NULL,
    descripcion text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.organizacion
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    nombre character varying NOT NULL,
    localizacion character varying NOT NULL,
    descripcion text NOT NULL,
    created_at time with time zone NOT NULL,
    updated_at time with time zone NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.usuario
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    nombre character varying NOT NULL,
    estado_id character varying NOT NULL,
    email character varying NOT NULL,
    password_hash character varying NOT NULL,
    created_at time with time zone NOT NULL,
    updated_at time with time zone NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.rol
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    nombre character varying NOT NULL,
    descripcion character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."planta"
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    nombre character varying NOT NULL,
    created_at time with time zone NOT NULL,
    updated_at time with time zone NOT NULL,
    fecha_inicio date NOT NULL,
    cultivo_id uuid NOT NULL,
    estado_planta_id uuid NOT NULL,
    cultivo_variedad_id uuid NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.evento
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    created_at time with time zone NOT NULL,
    updated_at time with time zone NOT NULL,
    tipo_evento_id uuid NOT NULL,
    descripcion text NOT NULL,
    fecha_inicio date NOT NULL,
    estado_evento_id uuid NOT NULL,
    usuario_id uuid NOT NULL,
    timeline_id uuid NOT NULL,
    cultivo_id uuid NOT NULL,
    planta_id uuid,
    planificacion_id uuid,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.registro
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    fecha_registro time with time zone NOT NULL,
    nombre character varying NOT NULL,
    parametro_temperatura numeric NOT NULL,
    parametro_humedad numeric NOT NULL,
    parametro_vpd numeric NOT NULL,
    parametro_co2 numeric,
    created_at time with time zone NOT NULL,
    updated_at time with time zone NOT NULL,
    cultivo_id uuid NOT NULL,
    usuario_id uuid NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.planificacion
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    nombre character varying NOT NULL,
    prioridad_id uuid NOT NULL,
    tipo_planificacion_id uuid NOT NULL,
    estado_planificacion_id uuid NOT NULL,
    fecha_planificacion date NOT NULL,
    fecha_fin_planificacion date,
    duracion_hs numeric,
    time_line_id uuid NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."timeLine"
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    nombre character varying NOT NULL,
    cultivo_id uuid NOT NULL,
    fecha_inicio date NOT NULL,
    fecha_real_inicio date NOT NULL,
    fecha_prevista_final date NOT NULL,
    fecha_real_fin date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."tipoEvento"
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    nombre character varying NOT NULL,
    descripcion text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."estadoEvento"
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    estado character varying NOT NULL,
    descripcion text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."faseCultivo"
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    nombre character varying NOT NULL,
    descripcion character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.cultivo
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    nombre character varying NOT NULL,
    fecha_inicio date NOT NULL,
    duracion_estimada numeric NOT NULL,
    fase_id uuid NOT NULL,
    estado_cultivo_id uuid NOT NULL,
    sala_id uuid NOT NULL,
    usuario_responsable_id uuid NOT NULL,
    cultivo_variedad_id uuid NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."estadoPlanta"
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    nombre character varying NOT NULL,
    descripcion text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."cultivoVariedad"
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    catalogo_variedad_id uuid NOT NULL,
    cantidad_plantas numeric NOT NULL,
    fecha_inicio date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."catalogoVariedad"
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    nombre character varying NOT NULL,
    banco character varying NOT NULL,
    tipo_variedad_id uuid NOT NULL,
    observaciones text,
    ciclo_completo_dias numeric NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."prioridadPlanificacion"
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    nombre character varying NOT NULL,
    nivel numeric NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."estadoPlanificacion"
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    nombre character varying NOT NULL,
    descripcion text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."tipoPlanificacion"
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    nombre character varying NOT NULL,
    descripcion text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.usuario_organizacion
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    usuario_id uuid NOT NULL,
    organizacion_id uuid NOT NULL,
    rol_id uuid NOT NULL,
    es_propietario boolean NOT NULL,
    created_at time with time zone NOT NULL,
    updated_at time with time zone NOT NULL,
    invitado_por uuid,
    estado_usuario_organizacion_id uuid NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."estadoCultivo"
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    nombre character varying NOT NULL,
    descripcion text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."estadoUsuarioOrganizacion"
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    nombre character varying NOT NULL,
    descripcion text,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.sala
    ADD FOREIGN KEY (organizacion_id)
    REFERENCES public.organizacion (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.sala
    ADD FOREIGN KEY (estado_sala_id)
    REFERENCES public.estado_sala (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.sala
    ADD FOREIGN KEY (tipo_sala_id)
    REFERENCES public.tipo_sala (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."planta"
    ADD FOREIGN KEY (cultivo_id)
    REFERENCES public.cultivo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."planta"
    ADD FOREIGN KEY (cultivo_variedad_id)
    REFERENCES public."cultivoVariedad" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.evento
    ADD FOREIGN KEY (cultivo_id)
    REFERENCES public.cultivo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.evento
    ADD FOREIGN KEY (timeline_id)
    REFERENCES public."timeLine" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.evento
    ADD FOREIGN KEY (estado_evento_id)
    REFERENCES public."estadoEvento" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.evento
    ADD FOREIGN KEY (tipo_evento_id)
    REFERENCES public."tipoEvento" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.evento
    ADD FOREIGN KEY (planta_id)
    REFERENCES public."planta" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.evento
    ADD FOREIGN KEY (usuario_id)
    REFERENCES public.usuario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.evento
    ADD FOREIGN KEY (planificacion_id)
    REFERENCES public.planificacion (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.registro
    ADD FOREIGN KEY (cultivo_id)
    REFERENCES public.cultivo (nombre) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.registro
    ADD FOREIGN KEY (usuario_id)
    REFERENCES public.usuario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.planificacion
    ADD FOREIGN KEY (time_line_id)
    REFERENCES public."timeLine" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.planificacion
    ADD FOREIGN KEY (prioridad_id)
    REFERENCES public."prioridadPlanificacion" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.planificacion
    ADD FOREIGN KEY (estado_planificacion_id)
    REFERENCES public."estadoPlanificacion" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.planificacion
    ADD FOREIGN KEY (tipo_planificacion_id)
    REFERENCES public."tipoPlanificacion" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."timeLine"
    ADD FOREIGN KEY (cultivo_id)
    REFERENCES public.cultivo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.cultivo
    ADD FOREIGN KEY (sala_id)
    REFERENCES public.sala (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.cultivo
    ADD FOREIGN KEY (usuario_responsable_id)
    REFERENCES public.usuario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.cultivo
    ADD FOREIGN KEY (fase_id)
    REFERENCES public."faseCultivo" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.cultivo
    ADD FOREIGN KEY (cultivo_variedad_id)
    REFERENCES public."cultivoVariedad" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.cultivo
    ADD FOREIGN KEY (estado_cultivo_id)
    REFERENCES public."estadoCultivo" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE public.planta
ADD CONSTRAINT fk_planta_estado
FOREIGN KEY (estado_planta_id)
REFERENCES public."estadoPlanta"(id);


ALTER TABLE IF EXISTS public."cultivoVariedad"
    ADD FOREIGN KEY (catalogo_variedad_id)
    REFERENCES public."catalogoVariedad" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.usuario_organizacion
    ADD FOREIGN KEY (usuario_id)
    REFERENCES public.usuario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.usuario_organizacion
    ADD FOREIGN KEY (organizacion_id)
    REFERENCES public.organizacion (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.usuario_organizacion
    ADD FOREIGN KEY (rol_id)
    REFERENCES public.rol (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.usuario_organizacion
    ADD FOREIGN KEY (estado_usuario_organizacion_id)
    REFERENCES public."estadoUsuarioOrganizacion" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;


